export const CURRENCIES = [
  { code: 'USD', symbol: '$', label: 'US Dollar' },
  { code: 'EUR', symbol: '€', label: 'Euro' },
  { code: 'GBP', symbol: '£', label: 'British Pound' },
  { code: 'JPY', symbol: '¥', label: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥', label: 'Chinese Yuan' },
  { code: 'AUD', symbol: 'A$', label: 'Australian Dollar' },
  { code: 'CAD', symbol: 'CA$', label: 'Canadian Dollar' },
  { code: 'CHF', symbol: 'Fr', label: 'Swiss Franc' },
  { code: 'HKD', symbol: 'HK$', label: 'Hong Kong Dollar' },
  { code: 'SGD', symbol: 'S$', label: 'Singapore Dollar' },
  { code: 'SEK', symbol: 'kr', label: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr', label: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr', label: 'Danish Krone' },
  { code: 'NZD', symbol: 'NZ$', label: 'New Zealand Dollar' },
  { code: 'KRW', symbol: '₩', label: 'South Korean Won' },
  { code: 'INR', symbol: '₹', label: 'Indian Rupee' },
  { code: 'BRL', symbol: 'R$', label: 'Brazilian Real' },
  { code: 'MXN', symbol: 'MX$', label: 'Mexican Peso' },
  { code: 'ZAR', symbol: 'R', label: 'South African Rand' },
  { code: 'RUB', symbol: '₽', label: 'Russian Ruble' },
  { code: 'TRY', symbol: '₺', label: 'Turkish Lira' },
  { code: 'AED', symbol: 'د.إ', label: 'UAE Dirham' },
  { code: 'SAR', symbol: '﷼', label: 'Saudi Riyal' },
  { code: 'QAR', symbol: 'QR', label: 'Qatari Riyal' },
  { code: 'KWD', symbol: 'KD', label: 'Kuwaiti Dinar' },
  { code: 'BHD', symbol: 'BD', label: 'Bahraini Dinar' },
  { code: 'OMR', symbol: 'ر.ع.', label: 'Omani Rial' },
  { code: 'ILS', symbol: '₪', label: 'Israeli Shekel' },
  { code: 'EGP', symbol: 'E£', label: 'Egyptian Pound' },
  { code: 'NGN', symbol: '₦', label: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', label: 'Kenyan Shilling' },
  { code: 'GHS', symbol: 'GH₵', label: 'Ghanaian Cedi' },
  { code: 'TZS', symbol: 'TSh', label: 'Tanzanian Shilling' },
  { code: 'UGX', symbol: 'USh', label: 'Ugandan Shilling' },
  { code: 'MAD', symbol: 'د.م.', label: 'Moroccan Dirham' },
  { code: 'TND', symbol: 'DT', label: 'Tunisian Dinar' },
  { code: 'DZD', symbol: 'دج', label: 'Algerian Dinar' },
  { code: 'THB', symbol: '฿', label: 'Thai Baht' },
  { code: 'IDR', symbol: 'Rp', label: 'Indonesian Rupiah' },
  { code: 'MYR', symbol: 'RM', label: 'Malaysian Ringgit' },
  { code: 'PHP', symbol: '₱', label: 'Philippine Peso' },
  { code: 'VND', symbol: '₫', label: 'Vietnamese Dong' },
  { code: 'TWD', symbol: 'NT$', label: 'Taiwan Dollar' },
  { code: 'PKR', symbol: '₨', label: 'Pakistani Rupee' },
  { code: 'BDT', symbol: '৳', label: 'Bangladeshi Taka' },
  { code: 'LKR', symbol: 'Rs', label: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: '₨', label: 'Nepalese Rupee' },
  { code: 'MMK', symbol: 'K', label: 'Myanmar Kyat' },
  { code: 'KHR', symbol: '៛', label: 'Cambodian Riel' },
  { code: 'LAK', symbol: '₭', label: 'Lao Kip' },
  { code: 'MNT', symbol: '₮', label: 'Mongolian Tugrik' },
  { code: 'PLN', symbol: 'zł', label: 'Polish Zloty' },
  { code: 'CZK', symbol: 'Kč', label: 'Czech Koruna' },
  { code: 'HUF', symbol: 'Ft', label: 'Hungarian Forint' },
  { code: 'RON', symbol: 'lei', label: 'Romanian Leu' },
  { code: 'BGN', symbol: 'лв', label: 'Bulgarian Lev' },
  { code: 'HRK', symbol: 'kn', label: 'Croatian Kuna' },
  { code: 'RSD', symbol: 'din', label: 'Serbian Dinar' },
  { code: 'UAH', symbol: '₴', label: 'Ukrainian Hryvnia' },
  { code: 'ISK', symbol: 'kr', label: 'Icelandic Krona' },
  { code: 'CLP', symbol: 'CL$', label: 'Chilean Peso' },
  { code: 'COP', symbol: 'CO$', label: 'Colombian Peso' },
  { code: 'PEN', symbol: 'S/.', label: 'Peruvian Sol' },
  { code: 'ARS', symbol: 'AR$', label: 'Argentine Peso' },
  { code: 'UYU', symbol: '$U', label: 'Uruguayan Peso' },
  { code: 'BOB', symbol: 'Bs.', label: 'Bolivian Boliviano' },
  { code: 'PYG', symbol: '₲', label: 'Paraguayan Guaraní' },
  { code: 'VES', symbol: 'Bs.S', label: 'Venezuelan Bolívar' },
  { code: 'GTQ', symbol: 'Q', label: 'Guatemalan Quetzal' },
  { code: 'HNL', symbol: 'L', label: 'Honduran Lempira' },
  { code: 'NIO', symbol: 'C$', label: 'Nicaraguan Córdoba' },
  { code: 'CRC', symbol: '₡', label: 'Costa Rican Colón' },
  { code: 'PAB', symbol: 'B/.', label: 'Panamanian Balboa' },
  { code: 'DOP', symbol: 'RD$', label: 'Dominican Peso' },
  { code: 'JMD', symbol: 'J$', label: 'Jamaican Dollar' },
  { code: 'TTD', symbol: 'TT$', label: 'Trinidad Dollar' },
  { code: 'BBD', symbol: 'Bds$', label: 'Barbadian Dollar' },
  { code: 'XCD', symbol: 'EC$', label: 'East Caribbean Dollar' },
  { code: 'BMD', symbol: 'BD$', label: 'Bermudian Dollar' },
  { code: 'KYD', symbol: 'CI$', label: 'Cayman Islands Dollar' },
  { code: 'AWG', symbol: 'ƒ', label: 'Aruban Florin' },
  { code: 'BSD', symbol: 'B$', label: 'Bahamian Dollar' },
  { code: 'HTG', symbol: 'G', label: 'Haitian Gourde' },
  { code: 'JOD', symbol: 'JD', label: 'Jordanian Dinar' },
  { code: 'LBP', symbol: 'L£', label: 'Lebanese Pound' },
  { code: 'SYP', symbol: '£S', label: 'Syrian Pound' },
  { code: 'IQD', symbol: 'ع.د', label: 'Iraqi Dinar' },
  { code: 'IRR', symbol: '﷼', label: 'Iranian Rial' },
  { code: 'AFN', symbol: '؋', label: 'Afghan Afghani' },
  { code: 'KZT', symbol: '₸', label: 'Kazakhstani Tenge' },
  { code: 'UZS', symbol: 'сўм', label: 'Uzbekistani Som' },
  { code: 'AZN', symbol: '₼', label: 'Azerbaijani Manat' },
  { code: 'GEL', symbol: '₾', label: 'Georgian Lari' },
  { code: 'AMD', symbol: '֏', label: 'Armenian Dram' },
  { code: 'MDL', symbol: 'L', label: 'Moldovan Leu' },
  { code: 'BYN', symbol: 'Br', label: 'Belarusian Ruble' },
  { code: 'GYD', symbol: 'GY$', label: 'Guyanese Dollar' },
  { code: 'SRD', symbol: 'Sr$', label: 'Surinamese Dollar' },
  { code: 'FJD', symbol: 'FJ$', label: 'Fijian Dollar' },
  { code: 'PGK', symbol: 'K', label: 'Papua New Guinean Kina' },
  { code: 'SBD', symbol: 'SI$', label: 'Solomon Islands Dollar' },
  { code: 'VUV', symbol: 'Vt', label: 'Vanuatu Vatu' },
  { code: 'WST', symbol: 'WS$', label: 'Samoan Tala' },
  { code: 'TOP', symbol: 'T$', label: 'Tongan Paʻanga' },
  { code: 'ANC', symbol: '✈', label: 'AeroNexus Credits (custom)' },
] as const;

export type CurrencyCode = typeof CURRENCIES[number]['code'];
